### ISSUE TITLE
Epic: Migrate docs files to docs repo

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#10]
For the next release of 1docs we need to combine multiple existing sources of documentation into this repo. Depending on the current location/format of each file they will need one of the following action items:

- The file already exists in `.mdx` and just needs to be moved over as is
- The file already exists in `.mdx`, it needs to be moved over and co-authors added
- the file already exists in `.ipynb`, it needs to be moved over and co-authors added
- The file already exists in `ipynb` in an open source repo and can be moved over as is (preserving authors and commit history)
- The file exists in `.rst` format, it needs to be moved over (preserving authors and commit history) and then converted to `.mdx`

**NOTE: to make this migration as smooth as possible we should aim to move the files over with as little changes to the content/pedagogy as possible. Many of these pages will indeed require content improvements at a later stage, but for this migration the only changes we should be making are adding co-authors, adjusting file names/paths, converting `.rst` to `.mdx`.**

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/docs/issues/21
- [ ] https://github.com/Qiskit/docs/issues/22
- [ ] https://github.com/Qiskit/docs/issues/23
```
