### ISSUE TITLE
[EPIC] Execution modes changes for 29 April

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1073]
I created an epic to keep track of all the changes required for the upcoming sessions release. Please add new issues to this epic. cc @jyu00 @beckykd 

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/595
- [ ] https://github.com/Qiskit/documentation/issues/1041
- [ ] https://github.com/Qiskit/documentation/issues/582
- [ ] https://github.com/Qiskit/documentation/issues/1081
- [ ] https://github.com/Qiskit/documentation/issues/1156
- [ ] #780
```
