### ISSUE TITLE
Epic: Prepare for open source contributions

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#11]
Before starting this epic we should decide the following:

- What types of contributions do we want to encourage/accept?
- Who should we accept contributions from?
- How can we make it as easy as possible for people to submit feedback or suggestions?
- How do we alert the appropriate people for new open issues and PRs?
- What branching/PR strategy should we enforce in this new repo -> do we need a dev contract?
- How should we document requirements/expectations/procedures for contributions?

```[tasklist]
### Tasks
- [x] Discussion: how do we want to handle contributions? (see questions above)
- [ ] https://github.com/Qiskit/docs/issues/12
- [ ] https://github.com/Qiskit/docs/issues/13
- [ ] https://github.com/Qiskit/docs/issues/50
- [ ] https://github.com/Qiskit/docs/issues/14
- [ ] https://github.com/Qiskit/docs/issues/53
- [ ] https://github.com/Qiskit/documentation/issues/109
```
