### ISSUE TITLE
[EPIC] Revamp existing open tutorials

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1134]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/1135
- [ ] https://github.com/Qiskit/documentation/issues/1136
- [ ] https://github.com/Qiskit/documentation/issues/1137
- [ ] https://github.com/Qiskit/documentation/issues/1138
- [ ] https://github.com/Qiskit/documentation/issues/1139
- [ ] https://github.com/Qiskit/documentation/issues/1140
- [ ] https://github.com/Qiskit/documentation/issues/1141
- [ ] move WIP open tutorials to this repo
```
