### ISSUE TITLE
[ EPIC ] Revamp WIP tutorials for open users

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1164]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/1166
- [ ] https://github.com/Qiskit/documentation/issues/1167
- [ ] https://github.com/Qiskit/documentation/issues/1168
- [ ] https://github.com/Qiskit/documentation/issues/1165
- [ ] https://github.com/Qiskit/documentation/issues/1169
- [ ] https://github.com/Qiskit/documentation/issues/1170
- [ ] https://github.com/Qiskit/documentation/issues/1171
- [ ] https://github.com/Qiskit/documentation/issues/1172
```

**Comment by frankharkins** [comment]
Seems to be completed
