### ISSUE TITLE
[EPIC] revamp left ToC for API docs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1213]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/1211
- [ ] https://github.com/Qiskit/documentation/issues/1248
- [ ] https://github.com/Qiskit/documentation/issues/1212
- [ ] https://github.com/Qiskit/documentation/pull/1246
- [ ] https://github.com/Qiskit/documentation/issues/1240
- [ ] https://github.com/Qiskit/documentation/issues/1242
- [ ] https://github.com/Qiskit/documentation/issues/1249
```
