### ISSUE TITLE
Sessions changes

### ISSUE THREAD

**Issue by beckykd** [Qiskit/documentation#124]
I have drafted content for the marked off boxes:

- [x]  1 min TTL: https://github.ibm.com/ibm-q-software/ws-qiskit-runtime-api/issues/247#issuecomment-63518888 and https://github.ibm.com/IBM-Q-Software/ws-multi-channel-scheduler/issues/142

- [x]  Get session details: https://github.ibm.com/IBM-Q-Software/sw-api-iqp/pull/418

- [ ] Limit max TTL per plan: https://github.ibm.com/ibm-q-software/cl-quantum-premium/issues/221

- [x] Accepting jobs flag: https://github.ibm.com/IBM-Q-Software/requirements-and-priorities/issues/207

No longer in plan:
- [ ] Extended sessions: https://github.ibm.com/ibm-q-software/cl-quantum-premium/issues/222 and https://github.ibm.com/IBM-Q-Software/requirements-and-priorities/issues/232

### If this new content request is accepted, will you write a draft the content, or help the team draft it?

I will write a draft of the proposed content

**Comment by mriedem** [comment]
> Extended sessions: https://github.ibm.com/ibm-q-software/cl-quantum-premium/issues/222 and https://github.ibm.com/IBM-Q-Software/requirements-and-priorities/issues/232

Hold off on making any external doc updates for extended sessions, i.e. active ttl windows being different from max ttl. Decision was made to only change active/max ttl values for IQP `Internal` hubs for now. cc @jyu00 @beckykd
