### ISSUE TITLE
Tutorial housekeeping

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1286]
There are some small differences between all the existing tutorials that we should clean up.

All the tutorials currently on learning:

- should use the same wording for each pattern step heading
- should include a list of requirements at the start
- should not include the author names at the top (there are some tutorials that were created from events that include the names)
- should include an estimated time the notebook takes to run, as well as the system it was tested on 

This issue applies to both open and network tutorials
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/pull/1379
- [ ] https://github.com/Qiskit/documentation/pull/1518
- [ ] https://github.com/Qiskit/documentation/pull/1519
- [ ] https://github.com/Qiskit/documentation/pull/1521
- [ ] https://github.com/Qiskit/documentation/pull/1531
- [ ] https://github.com/Qiskit/documentation/pull/1540
```

**Comment by abbycross** [comment]
Related issue: #1189

**Comment by javabster** [comment]
I wasnt able to find a single tutorial that does everything we want, but here are a couple that have good stuff:

- For consistent subheading naming checkout this one: https://learning.quantum.ibm.com/tutorial/quantum-approximate-optimization-algorithm
- for the requirements bullet list this PR: https://github.com/Qiskit/documentation/pull/1195/files

**Comment by javabster** [comment]
The tutorials that should be reviewed as part of this PR:

- https://learning.quantum.ibm.com/tutorial/variational-quantum-eigensolver
- https://learning.quantum.ibm.com/tutorial/quantum-approximate-optimization-algorithm
- https://learning.quantum.ibm.com/tutorial/chsh-inequality
- https://learning.quantum.ibm.com/tutorial/max-cut
- https://learning.quantum.ibm.com/tutorial/heisenberg-chain
- https://learning.quantum.ibm.com/tutorial/grovers-algorithm
- https://learning.quantum.ibm.com/tutorial/quantum-kernel-training
- https://learning.quantum.ibm.com/tutorial/submit-transpiled-circuits
- https://learning.quantum.ibm.com/tutorial/repeat-until-success
- https://learning.quantum.ibm.com/tutorial/build-repetition-codes

**Comment by javabster** [comment]
another thing that would be good to add to each tutorial (but not sure how feasible it is) is an estimate of how much QPU time it takes. e.g. could this tutorial be run within the 10min open plan, or is it many hours so recommended to use serverless

**Comment by javabster** [comment]
example notice:

QPU time estimate:
This tutorial took X QPU minutes when run using Y backend on Z date
NOTE: this is an estimate only, your runtimes may vary

**Comment by abbycross** [comment]
@beckykd pointed out that the tutorials have a little clock icon and a time listed, which is the estimated time it takes to read that tutorial. When we start listing the QPU time too, it has the potential to be confusing, especially since the time-to-read is not labeled (only with the icon, and there's no hover text).

@javabster do we want both times listed on every tutorial? If so, we might want to get design help to make it clearer what the clock icon time means, so as not to confuse with the QPU time that we list in the tutorial itself.

**Comment by beckykd** [comment]
@abbycross noticed that we have a couple of tutorials that start with a small example, then "beef it up" to be utility-scale (or closer).  Would that be a good pattern to follow everywhere?  It might make open users able to run more of the tutorials.

**Comment by beckykd** [comment]
@abbycross and I landed on this text:  

QPU time estimate: x minutes, y seconds  on ibm_xyz. (NOTE: This is an estimate only. Your runtime may vary.)

**Comment by beckykd** [comment]
> * For consistent subheading naming checkout this one

Some notes on this text:
1. There should not be periods in headings.
2. "Primitives" in "Qiskit primitives" should be lower case.

**Comment by beckykd** [comment]
> @abbycross and I landed on this text:
> 
> QPU time estimate: x minutes, y seconds on ibm_xyz. (NOTE: This is an estimate only. Your runtime may vary.)

Raul said that "Usage" would be a more accurate term than "QPU".
