### ISSUE TITLE
[epic] revamp how we test notebooks

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1326]
```[tasklist]
### Concurrency / queues
- [ ] https://github.com/Qiskit/documentation/pull/1150
- [ ] https://github.com/Qiskit/documentation/pull/1201
- [ ] https://github.com/Qiskit/documentation/issues/1323
- [ ] https://github.com/Qiskit/documentation/issues/1303
- [ ] https://github.com/Qiskit/documentation/issues/1229
```

```[tasklist]
### Usability
- [ ] https://github.com/Qiskit/documentation/pull/1207
- [ ] https://github.com/Qiskit/documentation/pull/1159
- [ ] https://github.com/Qiskit/documentation/pull/1049
- [ ] https://github.com/Qiskit/documentation/pull/897
- [ ] https://github.com/Qiskit/documentation/pull/734
- [ ] https://github.com/Qiskit/documentation/pull/527
- [ ] https://github.com/Qiskit/documentation/issues/1319
- [ ] https://github.com/Qiskit/documentation/issues/1239
- [ ] https://github.com/Qiskit/documentation/issues/967
- [ ] https://github.com/Qiskit/documentation/issues/920
```

```[tasklist]
### Better testing
- [ ] https://github.com/Qiskit/documentation/pull/483
- [ ] https://github.com/Qiskit/documentation/pull/1096
- [ ] https://github.com/Qiskit/documentation/pull/1184
- [ ] https://github.com/Qiskit/documentation/pull/1047
- [ ] https://github.com/Qiskit/documentation/pull/642
- [ ] https://github.com/Qiskit/documentation/pull/1333
- [ ] https://github.com/Qiskit/documentation/pull/1362
- [ ] https://github.com/Qiskit/documentation/pull/1373
```

```[tasklist]
### Closed source tutorials support
- [ ] https://github.com/Qiskit/documentation/pull/1208
- [ ] https://github.com/Qiskit/documentation/pull/1155
```

```[tasklist]
### Code quality
- [ ] https://github.com/Qiskit/documentation/pull/1351
- [ ] https://github.com/Qiskit/documentation/pull/1346
- [ ] https://github.com/Qiskit/documentation/pull/1397
```

**Comment by Eric-Arellano** [comment]
Closing as done. The follow up improvements can be tracked separately. Great work, Frank!
