### ISSUE TITLE
Rewrite intro pages

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#143]
Review and adjust the intro pages when the nav changes to Start - Build - Verify - Run.
```[tasklist]
### Tasks
- [x] Rewrite Start intro page
- [x] Rewrite Build intro page
- [x] Create Verify intro page
- [x] Rewrite Run intro page
```

**Comment by abbycross** [comment]
Comments from #137 from @blakejohnson (see [in context here](https://github.com/Qiskit/documentation/pull/137#discussion_r1354919916)):



Gates are not the only valid operations in a quantum circuits. So, I would suggest something to the effect of:

    are made up of operations including gates, measurement, and reset of qubits.




Ok, so some other things I think we need to do in the intro are to talk about what it is we are building. This effectively should signpost what is to come in the section. i.e. something like:

All tasks require building one or more quantum circuits. Some tasks additionally require constructing quantum operators to define properties of quantum states that we want to estimate/measure.

Qiskit enables working with circuits (and, to a lesser extent, operators) at various abstraction levels:

    abstract
    virtual
    physical
    scheduled
    pulse program
    At the most abstract level, we have a task-oriented lens in the circuit library. We can also express operations in abstract mathematical terms using Operators, isometries, and classical/boolean functions. Then we have virtual circuits where those mathematical abstractions take on a concrete representation in terms of a concrete gate set. At the physical level those instructions are mapped to specific physical qubits and instructions are re-written to reflect the connectivity and native gate set of a target hardware platform. Scheduled circuits introduce timing information. And finally pulse programs represent signals on channels.

Qiskit, and OpenQASM, further support the notion of extended circuits which expand the set of allowed operations to include real-time computations on classical values. Qiskit's tooling for working with this richer family of circuits is found in the section on Dynamic Circuits.
