### ISSUE TITLE
Epic: Revamp Start Section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#15]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/docs/issues/42
- [ ] https://github.com/Qiskit/documentation/issues/88
- [ ] https://github.com/Qiskit/documentation/issues/89
- [ ] https://github.com/Qiskit/documentation/issues/90
```
