### ISSUE TITLE
[EPIC] Fractional gates content

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1525]
### Tasks
- [ ] #1471
- [ ] https://github.com/Qiskit/documentation/issues/1526
- [ ] https://github.com/Qiskit/documentation/issues/1527
- [ ] https://github.com/Qiskit/documentation/issues/1528
- [ ] https://github.com/Qiskit/documentation/issues/1529
- [ ] Update runtime feature compatibility table to add fractional gates

tentative date: 1st July
