### ISSUE TITLE
Epic: Revamp Build Section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#16]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/100
- [ ] https://github.com/Qiskit/docs/issues/32
- [ ] https://github.com/Qiskit/docs/issues/40
- [ ] https://github.com/Qiskit/documentation/issues/92
- [ ] https://github.com/Qiskit/docs/issues/45
- [ ] https://github.com/Qiskit/docs/issues/39
- [ ] https://github.com/Qiskit/documentation/issues/152
- [ ] https://github.com/Qiskit/docs/issues/43
- [ ] https://github.com/Qiskit/docs/issues/46
- [ ] https://github.com/Qiskit/docs/issues/33
- [ ] https://github.com/Qiskit/documentation/issues/93
- [ ] https://github.com/Qiskit/documentation/issues/96
- [ ] https://github.com/Qiskit/documentation/issues/97
- [ ] https://github.com/Qiskit/documentation/issues/98
- [ ] https://github.com/Qiskit/documentation/issues/99
```
