### ISSUE TITLE
[ EPIC ] Update Qiskit Serverless docs

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1638]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/1639
- [ ] https://github.com/Qiskit/documentation/issues/1640
- [ ] https://github.com/Qiskit/documentation/issues/1641
- [ ] https://github.com/Qiskit/documentation/issues/1642
- [ ] https://github.com/Qiskit/documentation/issues/1643
- [ ] https://github.com/Qiskit/documentation/issues/1644
- [ ] https://github.com/Qiskit/documentation/issues/1645
- [ ] https://github.com/Qiskit/documentation/issues/1829
- [ ] https://github.com/Qiskit/documentation/issues/1828
```

final page structure should look like this:

- Qiskit Serverless (dropdown)
     - Intro to Qiskit Serverless (page)
     - Write your first serverless program (page)
     - Run workloads remotely (page)
     - Manage data and compute resources (page)

**Comment by Eric-Arellano** [comment]
The only remaining task is https://github.com/Qiskit/documentation/issues/1644, so I'm going to close this 🚀
