### ISSUE TITLE
Epic: Revamp Verify section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#17]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/docs/issues/29
- [x] Rename section "Test" to "Verify"
- [ ] Interview someone from Sarah's team about how they use simulators in utility-scale projects
- [ ] https://github.com/Qiskit/docs/issues/47
- [ ] https://github.com/Qiskit/documentation/issues/69
- [ ] https://github.com/Qiskit/documentation/issues/86
- [ ] https://github.com/Qiskit/documentation/issues/108
- [ ] https://github.com/Qiskit/documentation/issues/291
```

**Comment by kevinsung** [comment]
Here is my proposed plan for the Verify section:
- Rewrite Introduction (#86)
- Merge [IBM Quantum simulators](https://docs.quantum-computing.ibm.com/verify/cloud-based-simulators) and [Noisy simulators](https://docs.quantum-computing.ibm.com/verify/noisy-simulators) into a single page on IBM Quantum simulators and move to the end of the section
- Add page on noiseless and noisy simulation with Qiskit Aer
- Add page on noiseless and noisy (extended) stabilizer circuit simulation (#108)

In the end, the Verify section will have the following structure:
- Introduction
- Exact simulation with Qiskit primitives
- Exact and noisy simulation with Qiskit Aer primitives
- Build custom noise models
- Efficient (extended) stabilizer circuit simulation with Qiskit Aer
- IBM Quantum Simulators

**Comment by javabster** [comment]
@kevinsung i think this plan generally looks good to me, my only concern is that these pages might get quite long, so I'd recommend breaking them up and putting them under subheadings. We actually used to have the noisy simulation and ibm quantum simulators combined in one page as you suggest, but we split them to make it more readable.


So I'd recommend a page structure like this:
- Intro
- Qiskit Aer simulation
   - 	noiseless
   - noisy
- extended stabilizer simulation
   - noiseless
   - noisy
- IBM Quantum cloud-based simulation
   - available simulators
   - using the simulators


In addition, I'd be interested to hear any suggestions for expanding this section beyond just simulation, are there other "verification" steps that a user might want to take before running on real hardware that we might want to highlight here?

**Comment by blakejohnson** [comment]
> noisy (can you use noise models with primitives? Im not actually sure)

Yes, but to model the effect of various error mitigation techniques, you have to use the cloud simulators which we plan to sunset early in 2024. So, you can only locally simulate a primitive query without error mitigation.

It would be good to teach users to reason about the likelihood of success of a given circuit. i.e. maybe get them to extract the width and depth of their circuit, or extract the total number of cx gates. Even getting them to think about $p_{cx}^n$ where $p_{cx}$ is the average CX gate fidelity and $n$ is the number of gates would already be a start.

Eventually I would like to release tooling that counts layers in circuits in the same way we do within IBM's primitives, and then we can connect number of layers to the LEQ metric which will soon appear in the system cards.

**Comment by javabster** [comment]
final page structure:
- intro
- exact simulation with qiskit primitives
- noisy simulation with qiskit aer (including likelihood of success analysis)
- custom noise models with qiskit aer
- extended stabiliser simulation with qiskit aer
- IBM Quantum cloud-based simulation
    - available simulators
    - using the simulators

**Comment by kevinsung** [comment]
I decided not to include extended stabilizer simulation with the normal stabilizer simulation: https://github.com/Qiskit/documentation/pull/322.

The extended stabilizer simulation is different enough that it warrants its own page if we want to write one. There is already a good existing article though: https://qiskit.org/ecosystem/aer/tutorials/6_extended_stabilizer_tutorial.html. It uses `backend.run` but can be easily updated to use the Sampler primitive (but not the Estimator primitive because the simulator does not support expectation values).
