### ISSUE TITLE
[ EPIC ] Functions content

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#1700]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/1701
- [ ] https://github.com/Qiskit/documentation/issues/1702
- [ ] https://github.com/Qiskit/documentation/issues/1703
- [ ] https://github.com/Qiskit/documentation/issues/1704
- [ ] https://github.com/Qiskit/documentation/issues/1705
- [ ] Add functions to qiskit intro and patterns pages
```

cc @pandasa123
