### ISSUE TITLE
Epic: create new Transpile section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#18]
```[tasklist]
### Tasks
- [x] Content brainstorm with SMEs (Ali Javadi, Luciano Bello, Mat Treinish, Nick Bronn, Haimeng Zhang)
- [ ] https://github.com/Qiskit/docs/issues/28
- [ ] https://github.com/Qiskit/documentation/issues/101
- [ ] https://github.com/Qiskit/documentation/issues/103
- [ ] https://github.com/Qiskit/documentation/issues/104
- [ ] https://github.com/Qiskit/documentation/issues/211
- [ ] https://github.com/Qiskit/documentation/issues/102
- [ ] https://github.com/Qiskit/documentation/issues/106
- [ ] https://github.com/Qiskit/documentation/issues/126
- [ ] https://github.com/Qiskit/documentation/issues/107
- [ ] https://github.com/Qiskit/documentation/issues/105
```
