### ISSUE TITLE
[EPIC] Sphinx API docs redesign phase 2

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1808]
We made huge improvements to API docs in https://github.com/Qiskit/documentation/issues/479. This epic is to track other follow-up improvements we still want to make.

- [ ] https://github.com/Qiskit/documentation/issues/1098
- [x] https://github.com/Qiskit/documentation/issues/1388
- [ ] https://github.com/Qiskit/documentation/issues/1395
- [ ] https://github.com/Qiskit/documentation/issues/1361
