### ISSUE TITLE
[EPIC] API docs content improvements

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#1892]
This is focused on improving the content itself, unlike https://github.com/Qiskit/documentation/issues/1808 being focused on the visual design / web app.

### Infra tasks
- [ ] https://github.com/Qiskit/documentation/issues/818
- [x] https://github.com/Qiskit/documentation/issues/495
- [x] https://github.com/Qiskit/documentation/issues/1893

### Content tasks
- [x] https://github.com/Qiskit/documentation/issues/172
- [x] https://github.com/Qiskit/documentation/issues/1894
