### ISSUE TITLE
Epic: Revamp Run section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#19]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/docs/issues/26
- [ ] https://github.com/Qiskit/documentation/issues/114
- [ ] https://github.com/Qiskit/documentation/issues/110
- [ ] https://github.com/Qiskit/documentation/issues/115
- [ ] https://github.com/Qiskit/documentation/issues/111
- [ ] https://github.com/Qiskit/documentation/issues/112
- [ ] https://github.com/Qiskit/documentation/issues/116
- [ ] https://github.com/Qiskit/documentation/issues/148
```
