### ISSUE TITLE
Continue work on the "interoperate Qiskit with..." files

### ISSUE THREAD

**Issue by abbycross** [Qiskit/documentation#197]
As a followup to #151, finish resolving @jakelishman's comments and improvements to the `build/interoperate-qiskit-qasm2` and  `build/interoperate-qiskit-qasm3`  files
```[tasklist]
### Tasks
- [ ] Resolve [this comment](https://github.com/Qiskit/documentation/pull/151#discussion_r1362089872) on removing API duplication and linking out to API instead; just show examples
- [ ] Resolve [this comment](https://github.com/Qiskit/documentation/pull/151#discussion_r1362094395) on adding export instructions from qiskit to qasm3
- [ ] Resolve [this comment](https://github.com/Qiskit/documentation/pull/151#discussion_r1362096153) on changing to qasm2.loads and qasm3.loads
```
