### ISSUE TITLE
[epic] Handle inline classes in API docs

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#199]
https://qiskit.org/documentation/apidoc/qasm2.html#qiskit.qasm2.CustomClassical

<img width="726" alt="Screenshot 2023-10-18 at 1 14 51 PM" src="https://github.com/Qiskit/documentation/assets/14852634/a7e4ad05-2666-4c68-9520-e116f8069e8a">

It's more clear what is happening in open source:

<img width="824" alt="Screenshot 2023-10-18 at 1 15 04 PM" src="https://github.com/Qiskit/documentation/assets/14852634/e88a1cb2-503e-4c74-9f74-bff0f2532b7c">

```[tasklist]
### Tasks
https://github.com/Qiskit/documentation/issues/942
- [ ] https://github.com/Qiskit/documentation/issues/1215
- [ ] https://github.com/Qiskit/documentation/issues/1214
- [ ] https://github.com/Qiskit/documentation/issues/1276
```

**Comment by gracelindsell** [comment]
Designs have been finalized and can be found [here](https://www.figma.com/file/sNXucK1uMaZ8XXyLTZrdrs/IBM-Quantum-Documentation?type=design&node-id=4918%3A32646&mode=design&t=vSSxNBU0qL7pbjJp-1)

**Comment by Eric-Arellano** [comment]
Done. Thanks @arnaucasau!
