### ISSUE TITLE
Test functions notebooks in fortnightly cron job

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2239]
Investigate if we can test any of the functions notebooks in the fortnightly cron job.

**Todo:**
- [ ] Check which notebooks we can already test
- [ ] (Optional) Add feature to find/replace standardized strings like `<YOUR_API_TOKEN>` and `<YOUR_IQP_GROUP>` when testing
- [ ] Add testable notebooks to cron job

Large notebook changes are out of scope of this issue.
