### ISSUE TITLE
Use testing backends with functions notebooks

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/documentation#2240]
We can test functions that don't post-process results using the IBM test backends. This will submit jobs that should run very quickly and return nonsense results. We'll need to add some more patching code, but it'll hopefully mean we can test these notebooks on PR, which would be great.

**Todo:**

- [ ] Identify candidate notebooks (that is, any notebooks that don't post-process results)
- [ ] Add feature to patch these notebooks and prevent writing results
- [ ] Add candidate notebooks to PR checks
