### ISSUE TITLE
High priority improvements to /run

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#253]
```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/254
- [ ] https://github.com/Qiskit/documentation/issues/255
- [ ] https://github.com/Qiskit/documentation/issues/256
- [ ] https://github.com/Qiskit/documentation/issues/257
- [ ] https://github.com/Qiskit/documentation/issues/258
- [ ] https://github.com/Qiskit/documentation/issues/259
```
