### ISSUE TITLE
[REFACTOR] minor updates to the install page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#369]
Some minor improvements required to the install page for readability:

```[tasklist]
### Tasks
- [x] update release note links to not go to qiskit.org and go to the new release note pages in 1XP
- [x] in the platform support section, put the tier subheadings into markdown details objects
- [x] in the troubleshooting section put each error explanation into markdown details objects
```
