### ISSUE TITLE
Refactor "Summary of Quantum Operations" page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#44]
```[tasklist]
### Tasks
- [ ] page is very long, should be split into multiple pages (with better titles)
- [ ] avoid running the circuits where possible, unless relevant to understand the operation. the goal of the page is to teach people how to use the operations, not the full workflow of running them
- [ ] replace use of `BasicAer` with qiskit primitives
```
