### ISSUE TITLE
[Epic] Add translations to non-API docs.

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#476]
```[tasklist]
### Tasks
- [x] https://github.com/Qiskit/documentation/issues/7
- [x] https://github.com/Qiskit/documentation/pull/541
- [ ] Coordinate with designers to decide if the language switcher will be only for docs, or unified with Learning app
- [ ] Coordinate with ibm.com team to add language switcher & implement URL changing
- [ ] https://github.com/Qiskit/documentation/issues/185 and also ban using header anchors (except API docs)
```
