### ISSUE TITLE
[ EPIC ] Improve API Ref UX/UI

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#479]
We've been receiving a lot of feedback about the UX/UI of our API reference pages so I'm tracking them all together as one epic here. Some of these may be due to bugs in the API generation script, others might just be features that we forgot to include that were present in qiskit.org and now users are noticing they've disappeared. Either way they all come under the general umbrella of "things we should address to make the API references better". There may be some issues we could close as duplicates

```[tasklist]
### Information hierarchy / headers
- [ ] #231 
- [ ] #274 
- [ ] #167 
- [ ] #712
- [ ] #714
- [ ] https://github.com/Qiskit/documentation/issues/942
- [ ] https://github.com/Qiskit/documentation/issues/1276
- [ ] https://github.com/Qiskit/documentation/issues/941
- [ ] https://github.com/Qiskit/documentation/issues/932
- [ ] https://github.com/Qiskit/documentation/issues/1098
- [ ] https://github.com/Qiskit/documentation/issues/1215
- [ ] https://github.com/Qiskit/documentation/issues/1272
- [ ] https://github.com/Qiskit/documentation/issues/1196
- [ ] https://github.com/Qiskit/documentation/issues/1352
- [ ] https://github.com/Qiskit/documentation/issues/1388
- [ ] https://github.com/Qiskit/documentation/issues/1389
- [ ] https://github.com/Qiskit/documentation/issues/1395
```

```[tasklist]
### Visual design
- [ ] #521
- [ ] https://github.com/Qiskit/documentation/issues/948
- [ ] https://github.com/Qiskit/documentation/issues/947
- [ ] #735 
- [ ] #736
- [ ] https://github.com/Qiskit/documentation/issues/856
- [ ] https://github.com/Qiskit/documentation/issues/1216
- [ ]  #468 
- [ ] https://github.com/Qiskit/documentation/issues/1131
- [ ] https://github.com/Qiskit/documentation/issues/1287
- [ ] https://github.com/Qiskit/documentation/issues/1361
```

```[tasklist]
### Rendering bugs
- [ ] #59
- [ ] #732
- [ ] #488
- [ ] #485
- [ ] https://github.com/Qiskit/documentation/issues/814
- [ ] https://github.com/Qiskit/documentation/issues/769
- [ ] https://github.com/Qiskit/documentation/issues/755
- [ ] https://github.com/Qiskit/documentation/issues/1200
- [ ] https://github.com/Qiskit/documentation/issues/1199
- [ ] https://github.com/Qiskit/documentation/issues/1275
- [ ] https://github.com/Qiskit/documentation/issues/1217
- [ ] https://github.com/Qiskit/documentation/issues/1274
- [ ] https://github.com/Qiskit/qiskit/pull/11744
```

**Comment by Eric-Arellano** [comment]
Closing in favor of the more focused issue https://github.com/Qiskit/documentation/issues/1808 🚀
