### ISSUE TITLE
[ REFACTOR ] Small changes to simulators overview page

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#69]
page in question: https://docs.quantum-computing.ibm.com/test

Some small adjustments I think could improve the readability and usefulness of this page:
```[tasklist]
### Tasks
- [ ] change the heading titles to use the word simulator, so "Statevector Simulator", "Stabilizer Simulator" etc
- [ ] Add a sentence at the end of the overview section before launching into the descriptions of the simulators
- [ ] Add a minimum code example of how to use each simulator
```
