### ISSUE TITLE
[ EPIC ] Create/move pages for "Analyze Results" section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#839]
To have docs reflect the Qiskit patterns structure better we need some more content that supports users in the post-processing step of the patterns.

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/840
- [ ] https://github.com/Qiskit/documentation/issues/842
- [ ] https://github.com/Qiskit/documentation/issues/841
- [ ] https://github.com/Qiskit/documentation/issues/843
- [ ] create tab in top nav bar
```

**Comment by frankharkins** [comment]
This is complete
