### ISSUE TITLE
[ EPIC ] Convert "Transpile" section to "Optimize for hardware" section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#901]
As part of the transition towards patterns the "transpile" section of the docs should be refactored to represent the second step in the patterns workflow.

```[tasklist]
### Tasks
- [ ] https://github.com/Qiskit/documentation/issues/910
- [ ] https://github.com/Qiskit/documentation/issues/912
- [ ] https://github.com/Qiskit/documentation/issues/911
- [ ] https://github.com/Qiskit/documentation/issues/925
```
