### ISSUE TITLE
[ EPIC ] Create new "Deploy" section

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#905]
```[tasklist]
### Tasks
- [ ] Move quantum serverless page from "run" to "deploy" section
- [ ] Create new tab named "deploy"
- [ ] TBD: more serverless pages from Jen's team?
```

**Comment by javabster** [comment]
We are going in a different direction for patterns, this page will now live in a dedicated "serverless" section in the left sidebar of the "Guides" tab
