### ISSUE TITLE
[ EPIC ] Cloud simulator deprecation/removal

### ISSUE THREAD

**Issue by javabster** [Qiskit/documentation#918]
```[tasklist]
### Tasks
- [ ] #536 
- [ ] https://github.com/Qiskit/documentation/issues/919
- [ ] #607 
- [ ] https://github.com/Qiskit/documentation/issues/1031
- [ ] https://github.com/Qiskit/documentation/issues/1032
```

dates TBD

**Comment by abbycross** [comment]
This is complete.
